{% set version = "0.4.0" %}

package:
  name: intake-geopandas
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/i/intake_geopandas/intake_geopandas-{{ version }}.tar.gz
  sha256: 2a228fb8ff8d52bb0eb93d87d305dfa1c70875ea76f603dd7ba5b7b54c4dd884

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - geopandas
    - intake

test:
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check
  imports:
    - intake_geopandas

about:
  home: https://github.com/informatics-lab/intake_geopandas
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Geopandas plugin for Intake, providing drivers for Shapefiles, GeoJSON, PostGIS, and Spatialite

extra:
  recipe-maintainers:
    - ocefpaf
    - jhamman
