{% set version = "0.3.0" %}

package:
  name: intake-geopandas
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/i/intake_geopandas/intake_geopandas-{{ version }}.tar.gz
  sha256: b2bdf9978cd22bff6634cbd5075a8e0172bae88e28f5e9c9a62dbd9e274d90dc

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - geopandas
    - intake

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - intake_geopandas

about:
  home: https://github.com/informatics-lab/intake_geopandas
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Geopandas plugin for Intake, providing drivers for Shapefiles, GeoJSON, PostGIS, and Spatialite

extra:
  recipe-maintainers:
    - ocefpaf
    - jhamman
