{% set version = "0.2.4" %}

package:
  name: intake-geopandas
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/i/intake_geopandas/intake_geopandas-{{ version }}.tar.gz
  sha256: f94bacc0f499b56f5b71c52e018265755ba2b2b76169a5681802ec66f417f3ed

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - geopandas
    - intake

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - intake_geopandas

about:
  home: https://github.com/informatics-lab/intake_geopandas
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: "Geopandas plugin for Intake, providing drivers for Shapefiles, GeoJSON, PostGIS, and Spatialite"

extra:
  recipe-maintainers:
    - ocefpaf
